version: '3.8'
services:
  tocgame:
    container_name: Backend
    image: tocgame:22.47
  mongodb:
    container_name: mongodb
    environment:
     - PUID=1000
     - PGID=1000
    volumes:
     - /home/barry/mongodb/database:/data/db
    image: mongo:latest
    ports:
     - 27017:27017
    restart: unless-stopped