version: '3.8'
services:
  tocgame:
    container_name: Backend
    image: tocgame:22.47
    environment:
      MONGO_URL: "mongodb://mongodb:27017"
    depends_on:
      - mongodb
    ports:
     - 3000:3000
    restart: unless-stopped
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
     - ~/mongo/data:/data/db
    ports:
     - 27017:27017
    restart: unless-stopped